export const TABLE_DATA_REQUEST = "TABLE_DATA_REQUEST";
export const TABLE_DATA_sUCCESS = "TABLE_DATA_sUCCESS";
export const TABLE_DATA_FAIL = "TABLE_DATA_FAIL";

export const UPDATE_TABLE_DATA = "UPDATE_TABLE_DATA";
